   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 932.9 kB/s eta 0:00:13
   -- ------------------------------------- 0.8/12.3 MB 1.0 MB/s eta 0:00:12
   --- ------------------------------------ 1.0/12.3 MB 1.0 MB/s eta 0:00:11
   ---- ----------------------------------- 1.3/12.3 MB 1.1 MB/s eta 0:00:11
   ----- ---------------------------------- 1.6/12.3 MB 1.1 MB/s eta 0:00:10
   ----- ---------------------------------- 1.8/12.3 MB 1.2 MB/s eta 0:00:09
   ------- -------------------------------- 2.4/12.3 MB 1.4 MB/s eta 0:00:08
   --------- ------------------------------ 2.9/12.3 MB 1.5 MB/s eta 0:00:07
   ---------- ----------------------------- 3.1/12.3 MB 1.5 MB/s eta 0:00:07
   ----------- ----------

In [3]:
import numpy as np
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
print(arr)


[[1 2 3]
 [4 5 6]]
[1 2 3]


In [6]:
np.zeros((3, 3))
np.ones((2, 4))
np.eye(3)
np.arange(0, 10, 2)
np.linspace(0, 1, 5)
np.random.rand(3, 2)
np.random.randn(3, 2)


array([[ 0.21513246, -0.75341624],
       [-0.02939835,  1.6373793 ],
       [ 0.74281164,  0.5031604 ]])

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


(2, 3)
2
6
int64


In [7]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2, 4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.random.rand(3, 2)

array([[0.51662723, 0.32526746],
       [0.380199  , 0.75048127],
       [0.99497746, 0.38523016]])

In [13]:
np.random.randn(3, 2)

array([[ 1.93861301, -0.08557422],
       [-0.19885981,  0.55836096],
       [ 0.12410909,  0.75003356]])

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)
np.sin(a)


[5 7 9]
[ 4 10 18]


array([0.84147098, 0.90929743, 0.14112001])

In [18]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))
print(A @ B)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [20]:
arr = np.array([1, 2, 3, 4])
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())


10
2.5
4
1
1.118033988749895


In [21]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[1:4])
print(arr[::2])

 


1
[2 3 4]
[1 3 5]


In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1])
print(arr[:, 1])
print(arr[1, :2])

2
[2 5]
[4 5]


In [26]:
arr=np.arange(6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
a=np.array([1,2])
b=np.array([3,4])
print(np.concatenate((a,b)))
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[1 2 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]


In [32]:
a=np.array([1,2])
print(a+5)

[6 7]


In [37]:
loaded_arr = np.load('array.npy')


In [45]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.
